name: 'InfSharp'
description: 'InfSharp'
inputs:
  binary-path:
    description: 'The path where the binaries are located'
    required: true
  pr-changed-files:
    description: 'pr-changed-files'
    required: true
outputs:
  results:
    description: 'The analysis results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.binary-path }}
    - ${{ inputs.pr-changed-files }}
